name: build and norm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. リポジトリのコードをチェックアウト（コピー）してくる
    - uses: actions/checkout@v4

    # 2. Norminetteを動かすためにPython環境をセットアップする
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # 3. pipを使ってNorminetteをインストールする
    - name: Install Norminette
      run: |
        python -m pip install --upgrade pip
        pip install norminette

    # 4. Norminetteを実行する (エラーがあればここで止まる)
    - name: Run Norminette
      run: norminette .

    # 5. Makeを実行する
    - name: Run Make
      run: make
